/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgentDebugPanel: typeof import('./../../src/components/AgentDebugPanel.vue')['default']
    AgentProgress: typeof import('./../../src/components/AgentProgress.vue')['default']
    AnalysisResultPanel: typeof import('./../../src/components/presales/AnalysisResultPanel.vue')['default']
    AuthGlowShell: typeof import('./../../src/components/auth/AuthGlowShell.vue')['default']
    BrandLoader: typeof import('./../../src/components/loaders/BrandLoader.vue')['default']
    CallStrategy: typeof import('./../../src/components/sections/CallStrategy.vue')['default']
    ClientNeeds: typeof import('./../../src/components/sections/ClientNeeds.vue')['default']
    ClientTypeWidget: typeof import('./../../src/components/widgets/ClientTypeWidget.vue')['default']
    Compute: typeof import('./../../src/components/Compute.vue')['default']
    ConfidenceWidget: typeof import('./../../src/components/widgets/ConfidenceWidget.vue')['default']
    DiscoveryQuestions: typeof import('./../../src/components/sections/DiscoveryQuestions.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    FinalPrepNote: typeof import('./../../src/components/sections/FinalPrepNote.vue')['default']
    HomeComponent: typeof import('./../../src/views/home/components/HomeComponent.vue')['default']
    HomeModal: typeof import('./../../src/views/home/components/modals/HomeModal.vue')['default']
    HomeNestedComponent: typeof import('./../../src/views/home/components/nested/HomeNestedComponent.vue')['default']
    Icon: typeof import('./../../src/features/platform/icons/components/Icon.vue')['default']
    InputForm: typeof import('./../../src/components/InputForm.vue')['default']
    Modals: typeof import('./../../src/features/platform/modals/components/Modals.vue')['default']
    OpportunitySummary: typeof import('./../../src/components/sections/OpportunitySummary.vue')['default']
    ProposalDrawer: typeof import('./../../src/components/ProposalDrawer.vue')['default']
    ReportView: typeof import('./../../src/components/ReportView.vue')['default']
    Risks: typeof import('./../../src/components/sections/Risks.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SolutionApproach: typeof import('./../../src/components/sections/SolutionApproach.vue')['default']
    SplashScreen: typeof import('./../../src/components/SplashScreen.vue')['default']
    StepField: typeof import('./../../src/components/steps/StepField.vue')['default']
    StepForm: typeof import('./../../src/components/StepForm.vue')['default']
    SuggestedPitchWidget: typeof import('./../../src/components/widgets/SuggestedPitchWidget.vue')['default']
    SuggestedPositioning: typeof import('./../../src/components/sections/SuggestedPositioning.vue')['default']
    WidgetRow: typeof import('./../../src/components/widgets/WidgetRow.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}

// For TSX support
declare global {
  const AgentDebugPanel: typeof import('./../../src/components/AgentDebugPanel.vue')['default']
  const AgentProgress: typeof import('./../../src/components/AgentProgress.vue')['default']
  const AnalysisResultPanel: typeof import('./../../src/components/presales/AnalysisResultPanel.vue')['default']
  const AuthGlowShell: typeof import('./../../src/components/auth/AuthGlowShell.vue')['default']
  const BrandLoader: typeof import('./../../src/components/loaders/BrandLoader.vue')['default']
  const CallStrategy: typeof import('./../../src/components/sections/CallStrategy.vue')['default']
  const ClientNeeds: typeof import('./../../src/components/sections/ClientNeeds.vue')['default']
  const ClientTypeWidget: typeof import('./../../src/components/widgets/ClientTypeWidget.vue')['default']
  const Compute: typeof import('./../../src/components/Compute.vue')['default']
  const ConfidenceWidget: typeof import('./../../src/components/widgets/ConfidenceWidget.vue')['default']
  const DiscoveryQuestions: typeof import('./../../src/components/sections/DiscoveryQuestions.vue')['default']
  const ElAlert: typeof import('element-plus/es')['ElAlert']
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElCard: typeof import('element-plus/es')['ElCard']
  const ElCollapse: typeof import('element-plus/es')['ElCollapse']
  const ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
  const ElDrawer: typeof import('element-plus/es')['ElDrawer']
  const ElEmpty: typeof import('element-plus/es')['ElEmpty']
  const ElForm: typeof import('element-plus/es')['ElForm']
  const ElFormItem: typeof import('element-plus/es')['ElFormItem']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElTable: typeof import('element-plus/es')['ElTable']
  const ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
  const FinalPrepNote: typeof import('./../../src/components/sections/FinalPrepNote.vue')['default']
  const HomeComponent: typeof import('./../../src/views/home/components/HomeComponent.vue')['default']
  const HomeModal: typeof import('./../../src/views/home/components/modals/HomeModal.vue')['default']
  const HomeNestedComponent: typeof import('./../../src/views/home/components/nested/HomeNestedComponent.vue')['default']
  const Icon: typeof import('./../../src/features/platform/icons/components/Icon.vue')['default']
  const InputForm: typeof import('./../../src/components/InputForm.vue')['default']
  const Modals: typeof import('./../../src/features/platform/modals/components/Modals.vue')['default']
  const OpportunitySummary: typeof import('./../../src/components/sections/OpportunitySummary.vue')['default']
  const ProposalDrawer: typeof import('./../../src/components/ProposalDrawer.vue')['default']
  const ReportView: typeof import('./../../src/components/ReportView.vue')['default']
  const Risks: typeof import('./../../src/components/sections/Risks.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SolutionApproach: typeof import('./../../src/components/sections/SolutionApproach.vue')['default']
  const SplashScreen: typeof import('./../../src/components/SplashScreen.vue')['default']
  const StepField: typeof import('./../../src/components/steps/StepField.vue')['default']
  const StepForm: typeof import('./../../src/components/StepForm.vue')['default']
  const SuggestedPitchWidget: typeof import('./../../src/components/widgets/SuggestedPitchWidget.vue')['default']
  const SuggestedPositioning: typeof import('./../../src/components/sections/SuggestedPositioning.vue')['default']
  const WidgetRow: typeof import('./../../src/components/widgets/WidgetRow.vue')['default']
}